# Enable C++ Support
language: cpp
# Enable Sudo Support
sudo: required
dist: trusty

# Set the OS to Linux and macOS
os:
  - linux
  - osx

# Set the Compiler to GNU C++ and CLANG
compiler:
  - g++
  - clang

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_script: ./configure.sh

before_install: ./scripts/before_install.${TRAVIS_OS_NAME}.sh

script: make