# Enable C++ Support
language: cpp
# Enable Sudo Support
sudo: required
dist: trusty

# Set the OS to Linux and macOS
os:
  - osx

# Set the Compiler to GNU C++ and CLANG
compiler:
  - g++

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test

before_script: chmod +x configure.sh && ./configure.sh

before_install: chmod +x ./scripts/before_install.${TRAVIS_OS_NAME}.sh && ./scripts/before_install.${TRAVIS_OS_NAME}.sh

script: make