os:
 - linux
 - osx
osx_image: xcode8.2
language: cpp
branches:
  only:
  - master

sudo: required

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.9
            - g++-6
            - gcc-6

before_script: 
  - chmod +x configure.sh
  - ./configure.sh
 
script:
  - make all